### ISSUE TITLE
How to collect fully vaccinated data?

### ISSUE THREAD

**Issue by ligujie123** [bertrandmartel/tableau-scraping#14]
Hello,

I want to collect COVID vaccination data from Wisconsin (https://www.dhs.wisconsin.gov/covid-19/vaccine-data.htm#day) and Ohio (https://coronavirus.ohio.gov/wps/portal/gov/covid-19/dashboards/covid-19-vaccine/covid-19-vaccination-dashboard). More specifically, I am interested in how many people are fully vaccinated in each county for each race. Using your package, I could successfully collect vaccination data which is at least one dose, but cannot get fully vaccinated data. Can you help me to fix this problem, thanks!

<img width="993" alt="image" src="https://user-images.githubusercontent.com/29496632/119084690-3ea0e500-b9d0-11eb-9038-480fc0a9530f.png">
<img width="993" alt="image" src="https://user-images.githubusercontent.com/29496632/119084711-482a4d00-b9d0-11eb-8316-e71ab57191d9.png">

**Comment by ligujie123** [comment]
Hello,

I figured out how to collect fully vaccinated data at county-race level in Wisconsin. However, Ohio data is still tricky to collect. The key problem is: to collect fully vaccinated, race level data, there needs two parameters in the setParameter function (set 'values' to be 'Vaccine Completed**' and set 'Key Metrics' to be 'Race'). I am wondering whether setParameter function can set two parameters at the same time. Thanks!!

<img width="1073" alt="image" src="https://user-images.githubusercontent.com/29496632/119139031-90695f80-ba10-11eb-92b2-4c606d385805.png">

**Comment by ligujie123** [comment]
Hello,

I fix this by myself. Thanks.

**Comment by bertrandmartel** [comment]
@ligujie123 I'm glad you've fixed this. It seems I can't access this site in my location but I could use chromium on repl.it to investigate if you have other issues about it
