### ISSUE TITLE
Cannot locate function to manipulate drill/up down 

### ISSUE THREAD

**Issue by az-data-guru** [bertrandmartel/tableau-scraping#21]
URL: https://tableau.azdhs.gov/views/ELRv2testlevelandpeopletested/PeopleTested?%3Aembed=y

On the bottom left and right hand there is a plus/minus that calls a render-tooltip-server. The render-mode still shows client so I am unsure if this data can be extracted. I need to drill down to daily. Please let me know if I am missing something.

![vzresponse](https://user-images.githubusercontent.com/63130011/123018009-9db49980-d382-11eb-80cd-41c211106fb7.JPG)

**Comment by bertrandmartel** [comment]
I've just implemented the [level drill up/down](https://github.com/bertrandmartel/tableau-scraping#level-drill-updown) in v0.1.15. The following will drill down 3 times:

```python
from tableauscraper import TableauScraper as TS

url = 'https://tableau.azdhs.gov/views/ELRv2testlevelandpeopletested/PeopleTested'
ts = TS()
ts.loads(url)
wb = ts.getWorkbook()

sheetName = "P1 - Tests by Day W/ % Positivity (Both) (2)"

drillDown1 = wb.getWorksheet(sheetName).levelDrill(drillDown=True, position=1)
drillDown2 = drillDown1.getWorksheet(sheetName).levelDrill(drillDown=True, position=1)
drillDown3 = drillDown2.getWorksheet(sheetName).levelDrill(drillDown=True, position=1)

print(drillDown1.getWorksheet(sheetName).data)
print(drillDown2.getWorksheet(sheetName).data)
print(drillDown3.getWorksheet(sheetName).data)
```

[Try this on repl.it](https://replit.com/@bertrandmartel/TableauCovid19AzdhsPeopleTested)
