### ISSUE TITLE
dashboard.setDropdown() is not working.

### ISSUE THREAD

**Issue by yagoocarvalho** [bertrandmartel/tableau-scraping#3]
https://github.com/bertrandmartel/tableau-scraping/blob/93002c5a2a9d24d90793bccbea6e11f90a5e6380/scripts/dropdown_item.py#L19

I was testing the setDropdown script and found that the example script is not working. Parser works perfectly on dashboard first loaded data, but it doesn't work on the setDropdown response.

To reproduce the error just execute the script provided in the library (and referenced in this issue).

Hope you can find the issue and fix it.

Thank you very much

**Comment by bertrandmartel** [comment]
@yagoocarvalho Hello, sorry for the late response, this has been fixed in the new version 0.0.7
