### ISSUE TITLE
Specific worksheets only?

### ISSUE THREAD

**Issue by sidharthrajaram** [bertrandmartel/tableau-scraping#4]
Hey @bertrandmartel , this is such an  awesome library! Easy to use and super robust. 

Quick question, are there any ways to only get a specific worksheet when getting a dashboard (rather than looking through dashboard.worksheets afterwards)?

**Comment by bertrandmartel** [comment]
@sidharthrajaram Hello, yes you can get the worksheet directly using `getWorksheet("WORKSHEET_NAME")` like :

```
from tableauscraper import TableauScraper as TS

url = "https://public.tableau.com/views/PlayerStats-Top5Leagues20192020/OnePlayerSummary"

ts = TS()
ts.loads(url)

worksheet = ts.getWorksheet("ATT MID CREATIVE COMP")
print(worksheet.data)
```

**Comment by sidharthrajaram** [comment]
Great, thanks.
