### ISSUE TITLE
data coming back different than selected item

### ISSUE THREAD

**Issue by az-data-guru** [bertrandmartel/tableau-scraping#6]
Hi,

I am using this library to scrape a state tableau site for COVID-19 vaccine data. My goal is to eventually obtain all of the relevant county level data. However, when I select a county a different county's data comes back, with one county "Santa Cruz" not selecting anything. This may be an issue with the worksheet.

If it is an issue with the worksheet itself, is there any workaround I can use this to select the county via the map.

Thank you!

```python
from tableauscraper import TableauScraper as TS
import pandas as pd
import time

counties = ["Apache", "Coconino", "Cochise", "Graham", "Greenlee", "Gila", "La Paz", "Maricopa", "Mohave", "Navajo", "Pinal", "Pima",  "Yavapai", "Yuma"]


for county in counties:
    print(county)
    
    while True:
        try:
            data_list = []

            url = "https://tableau.azdhs.gov/views/VaccineDashboard/Vaccineadministrationdata?%3Aembed=y&"

            #initialize scraper

            ts = TS()
            ts.loads(url)

            #select that value
            dashboard = ts.getWorksheet(" County using admin county").select("Admin Address County W/ State Pod", county)

            for t in dashboard.worksheets:
                data_list.append(t.data)


            res = [int(i) for i in str(data_list[0]).split() if i.isdigit()]
            one_dose = res[1]
            print(one_dose)
            print(data_list[0])  
        except:
            continue
        break
    
    
    
    time.sleep(30)
```

**Comment by bertrandmartel** [comment]
@az-data-guru Do you use version v0.0.8 ? I've just released it today, it fixes some bug with select and dropDown

**Comment by az-data-guru** [comment]
I don't. I will update now and let you know. Thanks!

**Comment by az-data-guru** [comment]
It is still showing the wrong county.

**Comment by bertrandmartel** [comment]
@az-data-guru  I see, there is a bug related to the index of the values in the array. In all other tableau dashboard I've seen, the values were index from 1. But it seems in this case it starts from 2. With `Apache` being the last with value 16 while there are only 15 values.

Also you can move `ts = TS()` outside of the for loop (in order not to load a new session each time) and there is already a delay in the lib of `500` ms between select/dropdown calls. It can be changed with `ts = TS(delayMs=500)` 

```python
from tableauscraper import TableauScraper as TS

counties = ["Apache", "Coconino"]

url = "https://tableau.azdhs.gov/views/VaccineDashboard/Vaccineadministrationdata"

ts = TS()
ts.loads(url)
worksheet = ts.getWorksheet(" County using admin county")

values = ts.getWorksheet(" County using admin county").getValues("Admin Address County W/ State Pod")
print(values)

for county in counties:
    print(county)
    dashboard = worksheet.select("Admin Address County W/ State Pod", county)
    print(dashboard.getWorksheet("Number of People").data)
```

I will look at the raw data to see how to get that starting index issue

**Comment by bertrandmartel** [comment]
It seems there is an offset between the values index, it starts from 1 but from the 3rd one, the index is shifted :

"Yuma" 1
"Yavapai" 2
"Santa Cruz" 4
"Pinal" 5

**Comment by az-data-guru** [comment]
Thank you for catching that. This is something I would need to inform the tableau developer in order for it to work right?

Thank you!

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by bertrandmartel** [comment]
@az-data-guru  I don't know. This is the first time I notice an offset in the index of selection, there must be something in the data relating to those index. But maybe I'm missing something. It seems that there is no problem with the data since the tableau website can successfully get the data. Just that the Tableau website knows that SantaCruz is index 4 (an not 3) whereas I have no idea where this info is located in the json API result. 

I will continue to investigate tomorrow

**Comment by az-data-guru** [comment]
Thank you!

**Comment by bertrandmartel** [comment]
@az-data-guru  I've identified that there is a column `[system:visual].[tuple_id]` which points to:

```json
{
    "tupleIds": [
        1,
        2,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16
    ],
    "valueIndices": [],
    "aliasIndices": [],
    "formatstrIndices": []
},
```
This seems to be the way the index is built (called tupleId)

**Comment by bertrandmartel** [comment]
There is another bug related to #5. I need to look further into records of data dictionary chunks between calls

**Comment by bertrandmartel** [comment]
This is now working in v0.0.9 

The following get all the counties:

https://replit.com/@bertrandmartel/TableauCovidArizona
```python
from tableauscraper import TableauScraper as TS

url = "https://tableau.azdhs.gov/views/VaccineDashboard/Vaccineadministrationdata"

ts = TS()
ts.loads(url)
worksheet = ts.getWorksheet(" County using admin county")

counties = ts.getWorksheet(" County using admin county").getValues(
    "Admin Address County W/ State Pod")

for county in counties:
    print(county)
    dashboard = worksheet.select("Admin Address County W/ State Pod", county)
    print(dashboard.getWorksheet("Number of People").data)
```

**Comment by az-data-guru** [comment]
Thank you. It works now.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by bertrandmartel** [comment]
@az-data-guru Hello, there have been some improvement on the way the tuple index is used. If you want, you can move to v0.1.0, this would be 

```python
from tableauscraper import TableauScraper as TS

url = "https://tableau.azdhs.gov/views/VaccineDashboard/Vaccineadministrationdata"

ts = TS()
ts.loads(url)
ws = ts.getWorksheet(" County using admin county")

counties = [
  t["values"]
  for t in ws.getSelectableItems()
  if t["column"] == "Admin Address County W/ State Pod"
][0]

for county in counties:
    print(county)
    wb = ws.select("Admin Address County W/ State Pod", county)
    print(wb.getWorksheet("Number of People").data)
```
